package com.konductor.model;

import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class KonductorEventBuilderTest {

    @Test
    void happyPath_buildsEventWithAutoGeneratedIdAndTimestamp() {
        KonductorEvent event = KonductorEventBuilder.newEvent()
                .eventType("order.created")
                .sourceConfigId("order-service")
                .payload(Map.of("orderId", "abc", "amount", 99.5))
                .build();

        assertThat(event.getMetadata().getEventId()).isNotNull();
        assertThat(event.getMetadata().getEventTimestamp()).isNotNull();
        assertThat(event.getMetadata().getEventType()).isEqualTo("order.created");
        assertThat(event.getMetadata().getSourceConfigId()).isEqualTo("order-service");
        assertThat(event.getPayload()).containsKey("orderId");
        assertThat(event.getDataRefs()).isNull();
    }

    @Test
    void optionalFields_arePreserved() {
        DataRef ref = DataRef.builder()
                .uri("s3://bucket/key")
                .contentType("application/json")
                .checksum("abc123")
                .sizeBytes(1024L)
                .build();

        KonductorEvent event = KonductorEventBuilder.newEvent()
                .eventType("order.created")
                .sourceConfigId("order-service")
                .configType("REALTIME")
                .schemaVersion("1.0")
                .correlationId("corr-1")
                .traceId("trace-1")
                .payload(Map.of("orderId", "abc"))
                .dataRefs(List.of(ref))
                .build();

        assertThat(event.getMetadata().getConfigType()).isEqualTo("REALTIME");
        assertThat(event.getMetadata().getSchemaVersion()).isEqualTo("1.0");
        assertThat(event.getMetadata().getCorrelationId()).isEqualTo("corr-1");
        assertThat(event.getMetadata().getTraceId()).isEqualTo("trace-1");
        assertThat(event.getDataRefs()).hasSize(1);
        assertThat(event.getDataRefs().get(0).getUri()).isEqualTo("s3://bucket/key");
    }

    @Test
    void missingEventType_throws() {
        assertThatThrownBy(() -> KonductorEventBuilder.newEvent()
                .sourceConfigId("order-service")
                .payload(Map.of("key", "value"))
                .build())
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("eventType");
    }

    @Test
    void missingSourceConfigId_throws() {
        assertThatThrownBy(() -> KonductorEventBuilder.newEvent()
                .eventType("order.created")
                .payload(Map.of("key", "value"))
                .build())
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("sourceConfigId");
    }

    @Test
    void missingPayload_throws() {
        assertThatThrownBy(() -> KonductorEventBuilder.newEvent()
                .eventType("order.created")
                .sourceConfigId("order-service")
                .build())
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("payload");
    }

    @Test
    void blankEventType_throws() {
        assertThatThrownBy(() -> KonductorEventBuilder.newEvent()
                .eventType("  ")
                .sourceConfigId("order-service")
                .payload(Map.of("key", "value"))
                .build())
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("eventType");
    }
}
