spring:
  application:
    name: projector
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/konductor}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:projector}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.konductor.projector.kafka.message
        spring.json.value.default.type: com.konductor.projector.kafka.message.ProducerEventMessage
        spring.json.use.type.headers: false

konductor:
  kafka:
    source-events-topic: ${KONDUCTOR_SOURCE_EVENTS_TOPIC:konductor.source-events}

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info
