CREATE TABLE delivery_config (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    subscription_id BIGINT NOT NULL REFERENCES subscription(id) ON DELETE CASCADE,
    delivery_type VARCHAR(50) NOT NULL,
    endpoint_url TEXT,
    http_method VARCHAR(10),
    auth_type VARCHAR(50) NOT NULL DEFAULT 'NONE',
    auth_header_name VARCHAR(100),
    auth_secret_ref VARCHAR(300),
    timeout_seconds INTEGER NOT NULL DEFAULT 30,
    max_retry_count INTEGER NOT NULL DEFAULT 3,
    retry_backoff_seconds INTEGER NOT NULL DEFAULT 60,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by VARCHAR(320),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by VARCHAR(320),
    CONSTRAINT ck_delivery_timeout_positive CHECK (timeout_seconds > 0),
    CONSTRAINT ck_delivery_retry_count_non_negative CHECK (max_retry_count >= 0),
    CONSTRAINT ck_delivery_backoff_positive CHECK (retry_backoff_seconds > 0)
);
