CREATE TABLE event (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    event_uid VARCHAR(150) NOT NULL UNIQUE,
    source_event_id VARCHAR(150) NOT NULL,
    event_trigger_type_id SMALLINT NOT NULL REFERENCES event_trigger_type(id),
    subscription_id BIGINT NOT NULL REFERENCES subscription(id),
    event_trigger_selection_id BIGINT NOT NULL REFERENCES event_trigger_selection(id),
    delivery_config_id BIGINT REFERENCES delivery_config(id),
    event_status_id SMALLINT NOT NULL REFERENCES event_status(id),
    attempt_count INTEGER NOT NULL DEFAULT 0,
    last_attempt_at TIMESTAMPTZ,
    next_retry_at TIMESTAMPTZ,
    delivered_at TIMESTAMPTZ,
    response_status_code INTEGER,
    error_message TEXT,
    payload_hash VARCHAR(128),
    payload_size_bytes BIGINT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by VARCHAR(320),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by VARCHAR(320),
    CONSTRAINT ck_event_attempt_count_non_negative CHECK (attempt_count >= 0),
    CONSTRAINT ck_event_payload_size_non_negative CHECK (payload_size_bytes IS NULL OR payload_size_bytes >= 0)
);
